// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhF7vfE_o_Cnas3ZP-8SiMLk4KTKvqCyM',
    appId: '1:754104013067:web:a35139fa6a0f8e4975520e',
    messagingSenderId: '754104013067',
    projectId: 'studenttodo-64923',
    authDomain: 'studenttodo-64923.firebaseapp.com',
    storageBucket: 'studenttodo-64923.firebasestorage.app',
    measurementId: 'G-ET88DND6ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXyzokdXkvt_h-3Cq15rtGyvTUdTHpbo',
    appId: '1:754104013067:android:ed597d0ab94f4c9875520e',
    messagingSenderId: '754104013067',
    projectId: 'studenttodo-64923',
    storageBucket: 'studenttodo-64923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vX_fRldz6tSKgKllNC90_N9TfuOb_kc',
    appId: '1:754104013067:ios:4302734c61a76ae775520e',
    messagingSenderId: '754104013067',
    projectId: 'studenttodo-64923',
    storageBucket: 'studenttodo-64923.firebasestorage.app',
    iosBundleId: 'com.example.studenttodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vX_fRldz6tSKgKllNC90_N9TfuOb_kc',
    appId: '1:754104013067:ios:4302734c61a76ae775520e',
    messagingSenderId: '754104013067',
    projectId: 'studenttodo-64923',
    storageBucket: 'studenttodo-64923.firebasestorage.app',
    iosBundleId: 'com.example.studenttodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhF7vfE_o_Cnas3ZP-8SiMLk4KTKvqCyM',
    appId: '1:754104013067:web:911afb62ecdd89ed75520e',
    messagingSenderId: '754104013067',
    projectId: 'studenttodo-64923',
    authDomain: 'studenttodo-64923.firebaseapp.com',
    storageBucket: 'studenttodo-64923.firebasestorage.app',
    measurementId: 'G-F0RSEFS9XH',
  );
}
